name: Update Index

on:
  push:
    branches: [ main ]

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Generate index
      run: python indexer.py
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add index.json
        git add image_data.json
        git add images_path.json
        git commit -m 'Update index'
        git push
